package sabre;

import java.util.ArrayList;
import java.util.HashMap;

import javax.xml.ws.Holder;

import org.apache.camel.CamelContext;
import org.apache.camel.ProducerTemplate;
import org.apache.camel.component.cxf.CxfComponent;
import org.apache.camel.component.cxf.CxfEndpoint;
import org.apache.camel.impl.DefaultCamelContext;

import org.ebxml.namespaces.messageheader.From;
import org.ebxml.namespaces.messageheader.MessageHeader;
import org.ebxml.namespaces.messageheader.PartyId;
import org.ebxml.namespaces.messageheader.Service;
import org.ebxml.namespaces.messageheader.To;
import org.opentravel.ota._2002._11.SessionCreateRQ;
import org.opentravel.ota._2002._11.SessionCreateRQ.POS;
import org.opentravel.ota._2002._11.SessionCreateRQ.POS.Source;
import org.opentravel.ota._2002._11.SessionCreateRS;
import org.xmlsoap.schemas.ws._2002._12.secext.Security;
import org.xmlsoap.schemas.ws._2002._12.secext.Security.UsernameToken;

import https.webservices_sabre_com.websvc.SessionCreatePortType;

public class SessionCreate {

	public ArrayList buildRequest() {

		Holder<MessageHeader> 	messageHeader 	= new Holder<MessageHeader>();

		MessageHeader 			messageHeader2 	= new MessageHeader();
		Service 				service 		= new Service();
		messageHeader2.setAction("SessionCreateRQ");

		From 					from 			= new From();
		PartyId 				partyIdFrom 	= new PartyId();
		partyIdFrom.setValue("999999");
		from.getPartyId().add(partyIdFrom);
		messageHeader2.setFrom(from );

		To 						to 				= new To();
		PartyId 				partyIdTo 		= new PartyId();
		partyIdTo.setValue("123123");
		to.getPartyId().add(partyIdTo);
		messageHeader2.setTo(to);

		messageHeader2.setConversationId("abc123");
		messageHeader2.setCPAId("IPCC");

		messageHeader.value	= messageHeader2;




		Holder<Security> 		securityHeader 	= new Holder<Security>();
		Security 				security 		= new Security();

		UsernameToken usernameToken = new UsernameToken();
		usernameToken.setUsername("digitalmicroservices");
		usernameToken.setPassword("%m!GnUv6vEKY");
		usernameToken.setOrganization("IPCC");
		usernameToken.setDomain("DEFAULT");

		security.setUsernameToken(usernameToken );

		securityHeader.value = security;




		SessionCreateRQ sessionCreateRQ 		= new SessionCreateRQ();

		POS 			pos 					= new POS();
		Source 			source 					= new Source();

		source.setPseudoCityCode("IPCC");
		pos.setSource(source );
		sessionCreateRQ.setPOS(pos );

		// Request and response can be 'bare' or 'wrapped', see the service class.
		//		SessionCreateRS sessionCreateRS = template.requestBody(serviceEndpoint, messageHeader, SessionCreateRS.class);

		HashMap<String,Object> requestHeaders = new HashMap<String,Object>();
		requestHeaders.put("Username", usernameToken);

		ArrayList requestBody = new ArrayList();
		requestBody.add(messageHeader);
		requestBody.add(security);
		requestBody.add(sessionCreateRQ);

		return requestBody;

	}

	public SessionCreateRS invokeRequest(ArrayList requestBody) {

		CamelContext context = new DefaultCamelContext();

		CxfComponent cxfComponent = new CxfComponent(context);
		CxfEndpoint serviceEndpoint =
				new CxfEndpoint("https://webservices.sabre.com", cxfComponent);

		// Service class generated by CXF codegen plugin.
		serviceEndpoint.setServiceClass(SessionCreatePortType.class);

		ProducerTemplate template = context.createProducerTemplate();

		SessionCreateRS sessionCreateRS = template.requestBody(serviceEndpoint, requestBody, SessionCreateRS.class);
		
		return sessionCreateRS;


	}
	
	public String getSessionId(SessionCreateRS sessionCreateRS) {
		return sessionCreateRS.getConversationId();
	}

	String url = null;

}
